services:
  redis:
    container_name: mos-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: mos
    image: shoon95/mos:latest
    restart: always

    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "80:8080"